### ISSUE TITLE
dynamic-uses with actions with post steps

### ISSUE THREAD

**Issue by katarzynainit** [jenseng/dynamic-uses#15]
Hi

I'm having my own composite action that is called via jenseng/dynamic-uses. 
All works fine as long as I don't call action with post steps inside my composite action.

dynamic-uses
\_ my_composite_action
   \_ step1
   \_ step2
   \_ step3 with post code
   \_ step4

Basically this action with post steps (step3), does not have access to outputs from steps (step1, step2) in the post code.

Example composite action:

```
name: Test action

runs:
  using: 'composite'
  steps:
    - id: out
      shell: bash
      run: |
        echo "A=Aaaa" >> $GITHUB_OUTPUT
    
    - uses: gacts/run-and-post-run@v1
      with:
        run: |
          echo "RUN"
          echo "A=${{ steps.out.outputs.A }}"
        post: |
          echo "POST"
          echo "A=${{ steps.out.outputs.A }}"
```

All works fine when called from the workflow like this (Aaaa printed in both RUN and POST):
```
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/test
 ```

Aaaa is no longer printed when called via dynamic-uses, but only in POST call
```
  steps:
    - uses: actions/checkout@v4
    - uses: jenseng/dynamic-uses@v1
       with:
         uses: "./.github/actions/test"
```
