### ISSUE TITLE
Optionally unwrap an output

### ISSUE THREAD

**Issue by jenseng** [jenseng/dynamic-uses#17]
By default, dynamic-uses returns a single JSON output named `outputs` containing all the target action's outputs. Individual outputs can then be accessed via something like `fromJSON(steps.cool-action.outputs.outputs).theThingIWant`. This provides the most flexibility.

But sometimes just want a single output, and if you have to do this in multiple expressions this can get a bit tedious/verbose. It would be nice if you could optionally specify a particular output to target, then the `outputs` output would contain its actual value.

e.g. instead of this

```yaml
- id: cool-action
  uses: jenseng/dynamic-uses@v1
  with:
    uses: my/cool/action@${{ inputs.version }}
- env:
    theThing: ${{ fromJSON(steps.cool-action.outputs.outputs).theThingIWant }}
  run: echo "$theThing"
```

you could do something like this:

```yaml
- id: cool-action
  uses: jenseng/dynamic-uses@v1
  with:
    uses: my/cool/action@${{ inputs.version }}
    output: theThingIWant
- env:
    theThing: ${{ steps.cool-action.outputs.outputs }}
  run: echo "$theThing"
```

**Comment by ReenigneArcher** [comment]
How about grabbing the target's `action.yml` and parsing it with a yaml parser. Then injecting the original action's outputs into the temp action?

You should be able to download the `action.yml` file using https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content

**Comment by jsoref** [comment]
I'd probably just offer an action that generates an action that can parse things out.

```yaml
- uses: jenseng/dynamic-uses@v2
  with:
    unbox-output-action-path: parse-output
    uses: my/cool/action@${{ inputs.version }}
- uses: ./parse-output
  id: outputs
- env:
    color: ${{ steps.outputs.color }}
    fruit: ${{ steps.outputs.fruit }}
    tree: ${{ steps.outputs.tree }}
  run: |
    echo "color=$color; fruit=$fruit; tree=$tree"
```

It's certainly _possible_ for you to create a second action that has all of the outputs instead of just putting them in the github outputs output.
Obviously, you'd need to be careful.

As an initial implementation, you could require people to give the output from the dynamic-uses step to the parse-output step.

I haven't done such a thing yet, but, I'm certainly not above doing something like that.

I do have wrappers for things: https://github.com/check-spelling/check-spelling/tree/prerelease/actions and have toyed with automatically generating the wrappers...
