### ISSUE TITLE
Convert JSON to YAML array for Actions

### ISSUE THREAD

**Issue by cvega** [jenseng/dynamic-uses#3]
Hello @jenseng :wave:,

Just wanted to say thank you for this work, I have a use case where my next composite action cannot process `JSON`. I came up with this workaround/hack and wanted to share. Given the way this works already I'm not sure you could incorporate the change without breaking existing users. I'd be happy to create a new action and attribute you if so, let me know if you have any preferences or feedback. Thank you again.

TL;DR - convert `JSON` to a `YAML` array for actions.

![Screenshot 2023-05-15 at 10 29 02 AM](https://github.com/jenseng/dynamic-uses/assets/376532/a6e17fe4-8c69-42db-8eb3-c8a9f3825b3a)

```bash
format_json() {
  echo $1 | jq -r '
    (
      to_entries |
      reduce .[] as $item (" ";
        . + "\n                \($item.key | ascii_upcase): '\''\($item.value)'\''"
    )
  )'
}

export WITH=$(format_json '${{ inputs.with }}')

mkdir -p ./.tmp-dynamic-uses &&

cat << 'DYNAMIC_USES_EOF' | envsubst > ./.tmp-dynamic-uses/action.yml
outputs:
  outputs:
    value: ${{ '$' }}{{ toJSON(steps.run.outputs) }}
runs:
  using: composite
  steps:
    - name: Run
      id: run
      uses: ${{ inputs.uses }}
      with: ${WITH}
DYNAMIC_USES_EOF
```

**Comment by jenseng** [comment]
Thanks @cvega!

I'm curious why the existing approach doesn't work for you, since JSON is a subset of YAML. I wonder if it has to do with the fact that some of your values are arrays? It seems like `format_json` is converting them to strings (e.g. `[]` becomes `'[]'`), which I think is what's actually making it work, since all inputs need to be strings 🤔 

That makes me think that perhaps the action would work as-is if you explicitly stringified those arrays, e.g.

```yaml
- uses: jenseng/dynamic-uses@v1
  with:
    uses: .github/actions/org-webhook
    with: |
      {
        "INSTANCE": "COM",
        "ORGANIZATION": "casa-vega",
        "PAYLOAD_URL": "https://example.com/postlskdflsdjf",
        "CONTENT_TYPE": "json",
        "SECRET": "[]",
        "ACTIVE": "[\"Enable\"]",
        "EVENTS": "[\"check_run\", \"check_suite\"]",
        "HOSTNAME": "github"
      }
```

It's worth pointing out that if you call your action directly and don't stringify those arrays, it will also fail

```yaml
- uses: .github/actions/org-webhook
  with:
    INSTANCE: COM
    ORGANIZATION: casa-vega
    PAYLOAD_URL: https://example.com/postlskdflsdjf
    CONTENT_TYPE: json
    SECRET: [] # ❌  A sequence was not expected
    ACTIVE: ["Enable"] # ❌ A sequence was not expected
    EVENTS: ["check_run", "check_suite"] # ❌ A sequence was not expected
    HOSTNAME: github
```
