### ISSUE TITLE
Pass env down?

### ISSUE THREAD

**Issue by JonathanAtCenterEdge** [jenseng/dynamic-uses#5]
Given
```yaml
- uses: jenseng/dynamic-uses@v1
  with:
    uses: actions/setup-node@${{ steps.branch-name.outputs.current_branch }}
    with: '{ "node-version": 18 }'
  env:
    environment_variable: test
```
I don't believe `env` would be passed down into the dynamically created uses, this would be pretty integral to have as a feature
