### ISSUE TITLE
Passing secrets down?

### ISSUE THREAD

**Issue by milannakum** [jenseng/dynamic-uses#7]
With uses keyword, secrets can be passed by either providing key-values to `secrets` or passing down all secrets using `secrets: inherit` . Would it be possible with this github action? That might help prevent a lot of things needed to do for passing something like token or a client_secret or something.

**Comment by milannakum** [comment]
For reference: [Using inputs and secrets in a reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow)

**Comment by jenseng** [comment]
`dynamic-uses` is an action like any other, so you can the use the [secrets context](https://docs.github.com/en/actions/learn-github-actions/contexts#secrets-context) with it, no matter where those secrets come from (e.g. if they are regular repo secrets, or secrets passed into a reusable workflow). For example:

```yaml
- uses: jenseng/dynamic-uses@v1
  with:
    uses: my-cool/action@${{ inputs.version }}
    with: '{ "some-secret": ${{ toJSON(secrets.some-secret) }} }'
```

Or are you asking if `dynamic-uses` could somehow automatically pass secrets along to the action it's calling? I'm not quite sure how that would work. Unless I'm mistaken, you can't pass secrets to an action, except through `inputs` or `env`. Is your idea that the secrets would be converted into `inputs` of the same name?
