### ISSUE TITLE
Passing multiline secret down

### ISSUE THREAD

**Issue by fr12k** [jenseng/dynamic-uses#8]
Hi great work i really like the idea. The current problem i facing is to pass down a secret that contains a multiline string like a SSH Private Key for example.

Do you have any idea how to escape it properly so that i can be passed in the with block.

**Comment by jenseng** [comment]
Or a slightly different approach that keeps the bulk of the JSON stuff in the second step:

```yaml
jobs:
  my-job:
    steps:
      - id: jsonify
        env:
          multilineSecret: ${{ secrets.someSecret }}
        run: echo jsonSecret=$(echo "$multilineSecret"|jq -sR) >> "$GITHUB_OUTPUT"
      - uses: jenseng/dynamic-uses@v1
        with:
          uses: my-cool/action${{ inputs.actionRef }}
          with: |
            {
              "someInput": 1,
              "secret": ${{ steps.jsonify.outputs.jsonSecret }}
            }
```

**Comment by jenseng** [comment]
Oh hah, there's actually a much simpler way 😆 🤦

```yaml
jobs:
  my-job:
    steps:
      - uses: jenseng/dynamic-uses@v1
        with:
          uses: my-cool/action${{ inputs.actionRef }}
          with: |
            {
              "someInput": 1,
              "secret": ${{ toJSON(secrets.someSecret) }}
            }
```
